### PR TITLE
Skip expired certs in partial chain hook

### LINKED ISSUE #327: DST Root CA X3 expiration
When the DST Root CA X3 certificate expires on September 30 2021, certificate verification will fail for servers presenting Let's Encrypt's default 'long' chain on some Erlang/OTP versions.

Erlang/OTP versions prior to 23.3 are not affected: as long as the (now expired) DST Root CA X3 certificate is still present in the CA trust store, it will be trusted despite the expiry; once the certificate is removed, Mint's partial chain hook will make the cross-signed version of the ISRG root CA as trusted because it has the same public key as the ISRG root CA in the trust store.

Erlang/OTP versions [23.3.4.5](http://erlang.org/pipermail/erlang-questions/2021-July/101251.html) and later, as well as [24.0.4](http://erlang.org/pipermail/erlang-questions/2021-July/101252.html) and later are not effected as they include OTP-17475, which enables handling of alternate paths (actually making Mint's partial chain hook redundant).

On Erlang/OTP 23.3 till 23.3.4.4 and 24.0 till 24.0.3, Mint will fail to establish a connection to the server with Let's Encrypt's 'long' chain when the DST Root CA X3 certificate is still present in the trust store.

I previously thought the only solution was to remove the expired CA certificate from the trust store. But it turns out it is possible to work around this in the partial chain hook: if the certificate at the start of the chain has expired, the function should just drop it and recurse on the shorter chain. The next invocation will succeed because the cross-signed version of the ISRG root CA has the same public key as the ISRG root CA certificate in the trust store, and is therefore trusted.

### PR DESCRIPTION
**Pull request by voltone**
Fixes #327.

Opened as draft since I want to review the changes once more after clearing my head a bit, but it seems to work in testing...

BTW, note that on OTP 23.3.4.5 and 24.0.4 and later, `partial_chain` is no longer necessary at all. See https://blog.voltone.net/post/30. But I suppose it will be a good number of years before Mint can drop the `partial_chain` implementation.

### CODE REVIEW

**Comment by voltone** [comment]
Demonstrating the fix, starting by reproducing the problem described in #327:

```text
docker run -it --rm hexpm/elixir:1.12.2-erlang-23.3.4-ubuntu-focal-20210325                Mon Aug 30 09:07:30 2021
root@1d8f3da3f4da:/# apt update && apt install -y faketime ca-certificates git-core
[...snip...]
done.
root@1d8f3da3f4da:/# faketime '2021-10-01 09:00' iex
Erlang/OTP 23 [erts-11.2.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.12.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Mix.install([:castore, :mint], force: true)
[...snip...]
:ok
iex(2)> isrg = File.read!("/etc/ssl/certs/ISRG_Root_X1.pem") |> :public_key.pem_decode() |> hd() |> elem(1)
<<48, 130, 5, 107, 48, 130, 3, 83, 160, 3, 2, 1, 2, 2, 17, 0, 130, 16, 207, 176,
  210, 64, 227, 89, 68, 99, 224, 187, 99, 130, 139, 0, 48, 13, 6, 9, 42, 134,
  72, 134, 247, 13, 1, 1, 11, 5, 0, 48, 79, 49, ...>>
iex(3)> dst = File.read!("/etc/ssl/certs/DST_Root_CA_X3.pem") |> :public_key.pem_decode() |> hd() |> elem(1)
<<48, 130, 3, 74, 48, 130, 2, 50, 160, 3, 2, 1, 2, 2, 16, 68, 175, 176, 128,
  214, 163, 39, 186, 137, 48, 57, 134, 46, 248, 64, 107, 48, 13, 6, 9, 42, 134,
  72, 134, 247, 13, 1, 1, 5, 5, 0, 48, 63, 49, 36, ...>>
iex(4)> Mint.HTTP.connect(:https, "blog.voltone.net", 443, transport_opts: [reuse_sessions: false, cacerts: [isrg, dst]])

09:00:47.995 [info]  TLS :client: In state :certify at ssl_handshake.erl:1878 generated CLIENT ALERT: Fatal - Certificate Expired

{:error,
 %Mint.TransportError{
   reason: {:tls_alert,
    {:certificate_expired,
     'TLS client: In state certify at ssl_handshake.erl:1878 generated CLIENT ALERT: Fatal - Certificate Expired\n'}}
 }}
```

Here, Erlang/OTP selects the longest chain (with DST Root CA X3 as the root) and passes it to Mint's `partial_chain`. Because the public key of the first certificate matches a certificate in the trust store (the DST Root CA X3 certificate itself), Mint returns it as the trusted CA. Erlang/OTP then performs path validation with the entire chain, which fails on 23.3 or later because the first certificate in the chain has expired.

In the same container, starting a new IEx session with the branch from this PR:

```text
root@1d8f3da3f4da:/# faketime '2021-10-01 09:00' iex
Erlang/OTP 23 [erts-11.2.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.12.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Mix.install([:castore, {:mint, git: "https://github.com/voltone/mint", branch: "partial-chain-skip-expired"}], force: true)
[...snip...]
:ok
iex(2)> isrg = File.read!("/etc/ssl/certs/ISRG_Root_X1.pem") |> :public_key.pem_decode() |> hd() |> elem(1)
<<48, 130, 5, 107, 48, 130, 3, 83, 160, 3, 2, 1, 2, 2, 17, 0, 130, 16, 207, 176,
  210, 64, 227, 89, 68, 99, 224, 187, 99, 130, 139, 0, 48, 13, 6, 9, 42, 134,
  72, 134, 247, 13, 1, 1, 11, 5, 0, 48, 79, 49, ...>>
iex(3)> dst = File.read!("/etc/ssl/certs/DST_Root_CA_X3.pem") |> :public_key.pem_decode() |> hd() |> elem(1)
<<48, 130, 3, 74, 48, 130, 2, 50, 160, 3, 2, 1, 2, 2, 16, 68, 175, 176, 128,
  214, 163, 39, 186, 137, 48, 57, 134, 46, 248, 64, 107, 48, 13, 6, 9, 42, 134,
  72, 134, 247, 13, 1, 1, 5, 5, 0, 48, 63, 49, 36, ...>>
iex(4)> Mint.HTTP.connect(:https, "blog.voltone.net", 443, transport_opts: [reuse_sessions: false, cacerts: [isrg, dst]])
{:ok,
 %Mint.HTTP1{
  # ...snip...
 }}
```

Now Mint skips over the expired DST Root CA X3 in the chain, and starts looking for a trusted CA from the cross-signed ISRG Root X1 CA sent by the server. Since the public key of this certificate matches the ISRG Root X1 public key in the trust store, Mint returns it as the trusted CA. This time Erlang/OTP is happy with the (shortened) chain, since all certificates are valid.

Verification still works once the DST Root CA X3 certificate is removed from the trust store:

```text
iex(5)> Mint.HTTP.connect(:https, "blog.voltone.net", 443, transport_opts: [reuse_sessions: false, cacerts: [isrg]]) {:ok,
 %Mint.HTTP1{
  # ...snip...
 }}
```

**Comment by ericmj** [comment]
This is great, thank you! 

I have done an initial review and it looks good. Let us know when it's ready for final review.

💜💜💜💜💜💜

**Comment by voltone** [comment]
> Let us know when it's ready for final review.

I suppose it is. I will run a few more manual tests like the one above on other OTP versions, just to be sure. Should be able to do that later today...

**Comment by voltone** [comment]
Ok, additional testing with the following OTP versions was successful:

* 23.2.7 (pre-23.3)
* 23.3.4.5 (with alternate chain support in OTP)
* 24.0.3 (the 24.x equivalent of 23.3.4 as tested above)
* 24.0.4 (with alternate chain support in OTP)

Of these versions, only 23.0.3 requires the fix in this PR. The other versions do not require the fix; they were tested for regressions.

**Comment by whatyouhide** [comment]
@voltone did you do the testing manually? Do you think it would be beneficial to add those tests to CI?

**Comment by voltone** [comment]
Yes, the end-to-end tests were done manually, using my blog as the server. Testing them in CI would require a stable endpoint that presents a suitable chain, and that will continue to do so indefinitely. Most servers with a Let's Encrypt certificate would probably work, at least for the time being, however:

1. For tests to work between now and Oct 1st, the use of `faketime` would be needed
2. If `faketime` is used after Oct 1st, at some point the server cert will become invalid because it will have been issued in the future

How about I create a PR after Oct 1st that will check for regressions, without `faketime`?

**Comment by ericmj** [comment]
> How about I create a PR after Oct 1st that will check for regressions, without faketime?

That sounds like the most practical solution.

File: lib/mint/core/transport/ssl.ex [hunk 1]
```diff
@@ -642,12 +645,50 @@ defmodule Mint.Core.Transport.SSL do
...
+  end
+
+  defp to_datetime!(
+         <<year::binary-size(4), month::binary-size(2), day::binary-size(2), hour::binary-size(2),
+           minute::binary-size(2), second::binary-size(2), "Z"::binary>>
+       ) do
+    {:ok, datetime, _} =
+      DateTime.from_iso8601("#{year}-#{month}-#{day}T#{hour}:#{minute}:#{second}Z")
+
+    datetime
```
Comment (ericmj) [inline lib/mint/core/transport/ssl.ex:689]:
```suggestion
    DateTime.from_iso8601!("#{year}-#{month}-#{day}T#{hour}:#{minute}:#{second}Z")
```

File: test/mint/core/transport/ssl_test.exs [hunk 2]
```diff
@@ -270,11 +284,27 @@ defmodule Mint.Core.Transport.SSLTest do
     [cert: load_cert(@wildcard_san)]
   end
 
+  defp chain_with_expired_root(_context) do
+    [
+      chain: load_all_certs(@chain),
+      ca_store:
+        load_all_certs(@ca_store)
+        |> Enum.map(&:public_key.pkix_decode_cert(&1, :plain))
```
Comment (ericmj) [inline test/mint/core/transport/ssl_test.exs:292]:
```suggestion
      ca_store: Enum.map(load_all_certs(@ca_store), &:public_key.pkix_decode_cert(&1, :plain))
```

**Review by ericmj — APPROVED** [review]

File: lib/mint/core/transport/ssl.ex (hunk 1 above)
Comment (voltone) [reply lib/mint/core/transport/ssl.ex:689]: No such function in `DateTime`, I'm afraid. Only in `Date`, `Time` and `NaiveDateTime`...

Comment (voltone) [reply lib/mint/core/transport/ssl.ex:689]: There will be in 1.13, apparently...

**Comment by voltone** [comment]
Hey @ericmj @whatyouhide, will you be publishing a new release of Mint before the end of the month, in case people need it to resolve issues as a result of the DST Root CA expiry?

**Comment by ericmj** [comment]
Done!

Thanks again for your PR and research into this issue! 💜
